---

- name: Install git
  shell: bash -c "apk add git"

- name: Install curl
  shell: bash -c "apk add curl"

- name: Install supervisor
  shell: bash -c "apk add supervisor"

- name: Get glock
  shell: bash -c "go get github.com/robfig/glock"

- name: Symlink glock
  file: src="/usr/go/bin/glock"
        dest="{{ binaries_dir }}/glock"
        state=link

- name: Create logs directory
  shell: bash -c "mkdir -p /var/log/supervisor/alpine"

- name: Copy supervisord config
  copy: src=supervisor/alpine.conf dest=/etc/supervisord.conf